/*
 * Silex website builder, free/libre no-code tool for makers.
 * Copyright (c) 2023 lexoyo and Silex Labs foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @fileoverview
 * Defines the entry point of Silex client side application
 *
 */

import { SilexConfig } from './config'
import { initEditor, getEditor } from './grapesjs/index'
import { EVENT_STARTUP_START, EVENT_STARTUP_END } from '../events'

/**
 * Start Silex, called from host HTML page with window.silex.start()
 */
export async function start(options = {}) {
  const config = new SilexConfig()
  Object.assign(config, options)

  // Config file in root folder which can be generated by the server
  console.log('Loading config', config.clientConfigUrl)
  //import(/* webpackIgnore: true */ config.clientConfigUrl)
  //.then((configFile) => console.log('Config loaded', configFile))
  //.catch((e) => console.error('Config error', config.clientConfigUrl, e))
  await config.addPlugin(config.clientConfigUrl, {})

  // Debug mode
  if (config.debug) {
    console.warn('Silex starting in debug mode.', {config})
  }

  // Notify plugins that loading is over and Silex is starting
  config.emit(EVENT_STARTUP_START)

  // Start grapesjs
  console.log('start', {config})
  try{
    await initEditor(config.editor, config.grapesJsPlugins)
  } catch(e) {
    console.error('Error starting Silex', e)
    throw e
  }

  // Init internationalization module
  getEditor().I18n.setLocale(config.lang)

  // End of loading
  console.log('Silex started')
  document.querySelector('.silex-loader').classList.add('silex-dialog-hide')
  document.querySelector('#gjs').classList.remove('silex-dialog-hide')
  config.emit(EVENT_STARTUP_END)
}
