/*
 * Silex website builder - desktop app.
 * Copyright (c) 2023 lexoyo and Silex Labs foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 */

/*
 * MCP (Model Context Protocol) server for Silex Desktop.
 *
 * Static tools: website, take_screenshot.
 * Dynamic tools: loaded from the grapesjs-ai-capabilities registry
 * after a project is opened. Each capability becomes an MCP tool
 * that calls editor.runCommand() via eval_js.
 */

use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use base64::Engine;
use rmcp::handler::server::router::tool::{ToolRoute, ToolRouter};
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::*;
use rmcp::schemars::JsonSchema;
use rmcp::service::RequestContext;
use rmcp::transport::streamable_http_server::session::local::LocalSessionManager;
use rmcp::transport::streamable_http_server::StreamableHttpService;
use rmcp::{tool, tool_router, ErrorData as McpError, RoleServer, ServerHandler, ServiceExt};
use serde::Deserialize;
use tauri::Manager;
use tokio::sync::oneshot;

use crate::held::held;
use crate::AppState;

// ==========================================================================
// Shared state
// ==========================================================================

/// Pending eval results — shared between MCP tools and the HTTP callback handler.
pub type PendingEvals = Arc<std::sync::Mutex<HashMap<u64, oneshot::Sender<String>>>>;

// ==========================================================================
// Action enums (static tools only)
// ==========================================================================

#[derive(Debug, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum WebsiteAction {
    List,
    Create,
    Delete,
    Rename,
    Duplicate,
    Open,
    Dashboard,
}

// ==========================================================================
// Parameter structs (static tools only)
// ==========================================================================

#[derive(Debug, Deserialize, JsonSchema)]
pub struct WebsiteParams {
    /// The action to perform.
    pub action: WebsiteAction,
    /// Website ID (required for delete, rename, duplicate, open).
    pub website_id: Option<String>,
    /// Website name (required for create, rename).
    pub name: Option<String>,
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct ScreenshotParams {
    /// What to capture: "ui" for the whole editor (default),
    /// or "canvas" for only the website preview.
    pub target: Option<String>,
    /// File path to save the screenshot PNG to (optional, also returned inline as image).
    pub output_file: Option<String>,
}

// ==========================================================================
// SilexMcp struct
// ==========================================================================

#[derive(Clone)]
pub struct SilexMcp {
    /// Static tools (website, take_screenshot) generated by #[tool_router].
    tool_router: ToolRouter<Self>,
    /// Dynamic tools loaded from the grapesjs-ai-capabilities JS registry.
    dynamic_tools: Arc<tokio::sync::RwLock<ToolRouter<Self>>>,
    /// Whether dynamic capabilities have been loaded for this session.
    capabilities_loaded: Arc<std::sync::atomic::AtomicBool>,
    app_handle: tauri::AppHandle,
    eval_counter: Arc<AtomicU64>,
    pending_evals: PendingEvals,
}

// ==========================================================================
// Internal helpers
// ==========================================================================

impl SilexMcp {
    fn get_base_url(&self) -> String {
        self.app_handle
            .get_webview_window("main")
            .and_then(|w| w.url().ok())
            .map(|u| {
                format!(
                    "{}://{}:{}",
                    u.scheme(),
                    u.host_str().unwrap_or("localhost"),
                    u.port().unwrap_or(6805)
                )
            })
            .unwrap_or_else(|| "http://localhost:6805".to_string())
    }

    /// Navigate the webview to a URL (safe, no injection).
    fn navigate_to(&self, url: &str) -> Result<(), String> {
        let window = self
            .app_handle
            .get_webview_window("main")
            .ok_or_else(|| "No main window".to_string())?;
        let url_json =
            serde_json::to_string(url).map_err(|e| format!("Failed to encode URL: {}", e))?;
        window
            .eval(&format!("window.location.href = {}", url_json))
            .map_err(|e| format!("Navigation failed: {}", e))
    }

    /// Check that a project is open.
    fn require_project(&self) -> Result<(), String> {
        let state = self.app_handle.state::<AppState>();
        if held(&state.current_website_id).is_none() {
            return Err(
                "No project open. Use website(action: 'open') or website(action: 'create') first."
                    .into(),
            );
        }
        Ok(())
    }

    /// Execute JS in the webview and return the result.
    async fn eval_js_internal(
        &self,
        js_code: &str,
        timeout_secs: u64,
    ) -> Result<Option<String>, String> {
        let window = self
            .app_handle
            .get_webview_window("main")
            .ok_or_else(|| "No main window".to_string())?;

        if let Ok(url) = window.url() {
            let path = url.path();
            if path == "/" && url.query().is_none() {
                return Err(
                    "Editor not available — still on dashboard. Open or create a project first."
                        .to_string(),
                );
            }
        }

        let id = self.eval_counter.fetch_add(1, Ordering::Relaxed);
        let (tx, rx) = oneshot::channel::<String>();
        held(&self.pending_evals).insert(id, tx);

        let js_escaped =
            serde_json::to_string(js_code).map_err(|e| format!("Failed to escape JS: {}", e))?;

        let wrapped = r#"(async()=>{try{let __r=eval(__JS__);if(__r instanceof Promise)__r=await __r;const __s=(typeof __r==='undefined')?null:(typeof __r==='string')?__r:JSON.stringify(__r);await fetch(window.location.origin+'/eval-callback/__ID__',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({success:true,result:__s})})}catch(__e){await fetch(window.location.origin+'/eval-callback/__ID__',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({success:false,error:__e.message||String(__e)})})}})()"#
            .replace("__JS__", &js_escaped)
            .replace("__ID__", &id.to_string());

        window.eval(&wrapped).map_err(|e| {
            held(&self.pending_evals).remove(&id);
            format!("Failed to inject JS: {}", e)
        })?;

        let raw = tokio::time::timeout(std::time::Duration::from_secs(timeout_secs), rx)
            .await
            .map_err(|_| {
                held(&self.pending_evals).remove(&id);
                format!("Timeout waiting for JS result ({}s)", timeout_secs)
            })?
            .map_err(|_| {
                "Internal error: JS callback channel closed unexpectedly. Retry the operation."
                    .to_string()
            })?;

        #[derive(Deserialize)]
        struct JsResult {
            success: bool,
            result: Option<String>,
            error: Option<String>,
        }

        let parsed: JsResult =
            serde_json::from_str(&raw).map_err(|e| format!("Failed to parse JS result: {}", e))?;

        if parsed.success {
            Ok(parsed.result)
        } else {
            Err(parsed.error.unwrap_or_else(|| "Unknown JS error".into()))
        }
    }

    // ======================================================================
    // Dynamic capability loading
    // ======================================================================

    /// Load capabilities from the editor's JS registry and add as dynamic MCP tools.
    /// Called after a website is opened/created and the editor is ready.
    async fn load_capabilities(&self) -> Result<usize, String> {
        // Wait for capabilities to be registered (poll up to 30s).
        // The registry function exists early, but capabilities are registered
        // after the editor 'load' event fires 'ai-capabilities:ready'.
        // So we poll until getAllCapabilities() returns a non-empty array.
        let mut raw = "[]".to_string();
        let mut ready = false;
        for _ in 0..60 {
            let js = "JSON.stringify(window.__silexMcp?.getCapabilities?.() || [])";
            match self.eval_js_internal(js, 3).await {
                Ok(Some(val)) if val != "[]" && val.len() > 2 => {
                    raw = val;
                    ready = true;
                    break;
                }
                _ => {}
            }
            tokio::time::sleep(std::time::Duration::from_millis(500)).await;
        }
        if !ready {
            return Err("Editor capabilities not available after 30s".into());
        }

        #[derive(Deserialize)]
        struct CapDef {
            id: String,
            command: String,
            description: String,
            #[serde(rename = "inputSchema", default)]
            input_schema: Option<serde_json::Value>,
            #[serde(rename = "readOnly", default)]
            read_only: Option<bool>,
            #[serde(default)]
            destructive: Option<bool>,
            #[serde(default)]
            idempotent: Option<bool>,
            #[serde(rename = "openWorld", default)]
            open_world: Option<bool>,
        }

        let caps: Vec<CapDef> = serde_json::from_str(&raw)
            .map_err(|e| format!("Failed to parse capabilities: {}", e))?;

        let count = caps.len();
        let mut router = ToolRouter::new();

        for cap in caps {
            // Build the JSON Schema for the tool's input.
            // Ensure schema always has "type": "object" — some MCP clients
            // reject tools without a valid JSON Schema.
            let default_schema = serde_json::json!({"type": "object", "properties": {}});
            let schema_value = match cap.input_schema {
                Some(serde_json::Value::Object(ref m)) if m.contains_key("type") => {
                    cap.input_schema.unwrap()
                }
                _ => default_schema,
            };

            // Convert Value to JsonObject and sanitize property keys
            // (MCP clients require keys to match ^[a-zA-Z0-9_.-]{1,64})
            let schema_obj = match schema_value {
                serde_json::Value::Object(mut map) => {
                    if let Some(serde_json::Value::Object(props)) = map.remove("properties") {
                        let sanitized: serde_json::Map<String, serde_json::Value> = props
                            .into_iter()
                            .map(|(k, v)| (k.replace(':', "_"), v))
                            .collect();
                        map.insert("properties".into(), serde_json::Value::Object(sanitized));
                    }
                    map
                }
                _ => serde_json::Map::new(),
            };

            let annotations = ToolAnnotations {
                read_only_hint: cap.read_only.or(Some(false)),
                destructive_hint: if cap.read_only == Some(true) {
                    None
                } else {
                    cap.destructive.or(Some(false))
                },
                idempotent_hint: cap.idempotent,
                open_world_hint: cap.open_world,
                ..Default::default()
            };

            let tool = Tool {
                // ':' in capability ids is not allowed in tool names (clients require ^[a-zA-Z0-9_-]+$)
                name: cap.id.replace(':', "_").into(),
                title: None,
                description: Some(cap.description.into()),
                input_schema: Arc::new(schema_obj),
                output_schema: None,
                annotations: Some(annotations),
                execution: None,
                icons: None,
                meta: None,
            };

            let cap_command = Arc::new(cap.command);

            let route = ToolRoute::new_dyn(tool, move |ctx| {
                let cmd = cap_command.clone();
                Box::pin(async move {
                    let mcp: &SilexMcp = ctx.service;

                    // Get params as JSON object
                    let params_json = ctx
                        .arguments
                        .as_ref()
                        .map(|v| serde_json::Value::Object(v.clone()).to_string())
                        .unwrap_or_else(|| "{}".into());

                    let cmd_js = serde_json::to_string(cmd.as_str()).unwrap();
                    let params_js_escaped = serde_json::to_string(&params_json).unwrap();

                    // Await Promise results from runCommand so async commands
                    // (fonts:available, publish) return their real result/error.
                    let js = dynamic_command_js(&cmd_js, &params_js_escaped);
                    let timeout_secs = if cmd.as_str() == "fonts:available" {
                        30
                    } else {
                        10
                    };

                    mcp.require_project()
                        .map_err(|e| McpError::internal_error(e, None))?;
                    match mcp.eval_js_internal(&js, timeout_secs).await {
                        Ok(result) => Ok(finish_dynamic_tool(
                            cmd.as_str(),
                            result.unwrap_or_else(|| "null".into()),
                        )),
                        Err(e) => Ok(mcp.dynamic_tool_eval_error(e).await),
                    }
                })
            });

            router.add_route(route);
        }

        // Replace the dynamic tools router
        *self.dynamic_tools.write().await = router;
        self.capabilities_loaded.store(true, Ordering::Release);

        tracing::info!("Loaded {} dynamic capabilities as MCP tools", count);
        Ok(count)
    }

    /// A failed eval still tries to attach the current selection.
    async fn dynamic_tool_eval_error(&self, error: String) -> CallToolResult {
        let selection = match self
            .eval_js_internal(
                "JSON.stringify(window.__silexMcp&&window.silex?window.__silexMcp.getSelectionState(window.silex.getEditor()):null)",
                3,
            )
            .await
        {
            Ok(Some(raw)) => serde_json::from_str(&raw).ok(),
            _ => None,
        };
        finish_dynamic_error(error, selection)
    }
}

/// Create an error CallToolResult (is_error = true).
fn tool_error(msg: impl Into<String>) -> CallToolResult {
    CallToolResult {
        content: vec![Content::text(msg.into())],
        structured_content: None,
        is_error: Some(true),
        meta: None,
    }
}

const FONTS_PAGE_SIZE: usize = 20;

/// JS that runs a dynamic editor command and waits for a Promise result.
fn dynamic_command_js(cmd_js: &str, params_js: &str) -> String {
    format!(
        r#"(async function(){{var e=window.silex.getEditor();var params=JSON.parse({params});var cmd={cmd};var mcp=window.__silexMcp;var __result__;var __err__;try{{if(cmd==="publish"&&mcp&&typeof mcp.runPublish==="function"){{__result__=mcp.runPublish(e,params)}}else{{__result__=e.runCommand(cmd,params)}}if(__result__&&typeof __result__.then==="function")__result__=await __result__}}catch(ex){{__err__=ex.message||String(ex)}}var __sel__=mcp&&mcp.getSelectionState?mcp.getSelectionState(e):null;if(__err__)return JSON.stringify({{error:__err__,selection:__sel__}});if(typeof __result__==="undefined"||__result__===null)__result__={{}};if(typeof __result__==="string"){{try{{__result__=JSON.parse(__result__)}}catch(ex){{__result__={{raw:__result__}}}}}}if(Array.isArray(__result__))__result__={{result:__result__}};if(typeof __result__!=="object"||__result__===null)__result__={{result:__result__}};if(cmd==="fonts:available"&&window.__silexMcpDynamic)__result__=window.__silexMcpDynamic.pageFontsAvailable(__result__);__result__.selection=__sel__;return JSON.stringify(__result__)}})()"#,
        params = params_js,
        cmd = cmd_js
    )
}

fn command_is_error(value: &serde_json::Value) -> bool {
    value
        .get("error")
        .map_or(false, |e| !e.is_null() && e.as_str() != Some(""))
        || value.get("success").map_or(false, |s| s == false)
        || value.get("status").map_or(false, |s| s == "error")
}

fn page_fonts_available(mut value: serde_json::Value) -> serde_json::Value {
    if value.get("fonts").and_then(|v| v.as_array()).is_some()
        && value.get("remaining").and_then(|v| v.as_u64()).is_some()
    {
        return value;
    }

    let list = if let Some(arr) = value.get("result").and_then(|v| v.as_array()).cloned() {
        value.as_object_mut().map(|obj| obj.remove("result"));
        arr
    } else if let Some(arr) = value.get("fonts").and_then(|v| v.as_array()).cloned() {
        arr
    } else if let Some(arr) = value.as_array().cloned() {
        value = serde_json::json!({});
        arr
    } else {
        return value;
    };

    let remaining = list.len().saturating_sub(FONTS_PAGE_SIZE);
    let fonts: Vec<serde_json::Value> = list.into_iter().take(FONTS_PAGE_SIZE).collect();
    if !value.is_object() {
        value = serde_json::json!({});
    }
    let obj = value.as_object_mut().unwrap();
    obj.insert("fonts".into(), serde_json::Value::Array(fonts));
    obj.insert("remaining".into(), serde_json::json!(remaining));
    if remaining > 0 {
        obj.insert(
            "hint".into(),
            serde_json::json!(format!(
                "{} more fonts available. Use search to narrow the list.",
                remaining
            )),
        );
    } else {
        obj.remove("hint");
    }
    value
}

/// Always keep `selection`. `warnings` stay only when the tool failed.
fn normalize_tool_payload(mut value: serde_json::Value, is_error: bool) -> serde_json::Value {
    if !value.is_object() {
        value = serde_json::json!({ "result": value });
    }
    if !is_error {
        if let Some(sel) = value.get_mut("selection").and_then(|s| s.as_object_mut()) {
            sel.remove("warnings");
        }
        value.as_object_mut().unwrap().remove("warnings");
    }
    value
}

fn dynamic_tool_payload(command: &str, text: String) -> (serde_json::Value, bool) {
    let mut value = serde_json::from_str::<serde_json::Value>(&text)
        .unwrap_or_else(|_| serde_json::json!({ "raw": text }));
    if command == "fonts:available" {
        value = page_fonts_available(value);
    }
    let is_error = command_is_error(&value);
    (normalize_tool_payload(value, is_error), is_error)
}

fn finish_dynamic_tool(command: &str, text: String) -> CallToolResult {
    let (value, is_error) = dynamic_tool_payload(command, text);
    CallToolResult {
        content: vec![Content::text(value.to_string())],
        structured_content: None,
        is_error: if is_error { Some(true) } else { None },
        meta: None,
    }
}

fn dynamic_error_payload(
    error: impl Into<String>,
    selection: Option<serde_json::Value>,
) -> serde_json::Value {
    let mut value = serde_json::json!({ "error": error.into() });
    if let Some(sel) = selection {
        if !sel.is_null() {
            value["selection"] = sel;
        }
    }
    normalize_tool_payload(value, true)
}

fn finish_dynamic_error(
    error: impl Into<String>,
    selection: Option<serde_json::Value>,
) -> CallToolResult {
    let value = dynamic_error_payload(error, selection);
    CallToolResult {
        content: vec![Content::text(value.to_string())],
        structured_content: None,
        is_error: Some(true),
        meta: None,
    }
}

// ==========================================================================
// Static tool implementations
// ==========================================================================

#[tool_router]
impl SilexMcp {
    pub fn new(
        app_handle: tauri::AppHandle,
        pending_evals: PendingEvals,
        eval_counter: Arc<AtomicU64>,
        dynamic_tools: Arc<tokio::sync::RwLock<ToolRouter<Self>>>,
        capabilities_loaded: Arc<std::sync::atomic::AtomicBool>,
    ) -> Self {
        Self {
            tool_router: Self::tool_router(),
            dynamic_tools,
            capabilities_loaded,
            app_handle,
            eval_counter,
            pending_evals,
        }
    }

    /// Start a Sentry transaction for an MCP tool call.
    fn start_tool_transaction(tool_name: &str, action: &str) -> sentry::TransactionOrSpan {
        let tx_ctx = sentry::TransactionContext::new(&format!("mcp/{}", tool_name), "mcp.tool");
        let transaction = sentry::start_transaction(tx_ctx);
        transaction.set_data("action", serde_json::Value::String(action.to_string()));
        transaction.into()
    }

    // ----------------------------------------------------------------------
    // website — list, create, delete, rename, duplicate, open, dashboard
    // ----------------------------------------------------------------------

    #[tool(
        description = "Manage websites in the Silex visual website builder. Actions: list, create, delete, rename, duplicate, open, dashboard. After create or open, new editor tools are loaded dynamically — call list_tools to discover them. Use dashboard to return to the website list."
    )]
    async fn website(
        &self,
        Parameters(params): Parameters<WebsiteParams>,
    ) -> Result<CallToolResult, McpError> {
        let _tx = Self::start_tool_transaction("website", &format!("{:?}", params.action));
        let base_url = self.get_base_url();
        let client = reqwest::Client::new();

        match params.action {
            WebsiteAction::List => {
                let url = format!("{}/api/website", base_url);
                match reqwest::get(&url).await {
                    Ok(resp) => match resp.text().await {
                        Ok(body) => Ok(CallToolResult::success(vec![Content::text(body)])),
                        Err(e) => Ok(tool_error(format!("Error reading response: {}", e))),
                    },
                    Err(e) => Ok(tool_error(format!("Error fetching websites: {}", e))),
                }
            }

            WebsiteAction::Create => {
                let url = format!("{}/api/website?connectorId=fs-storage", base_url);
                let body = if let Some(name) = &params.name {
                    serde_json::json!({ "name": name })
                } else {
                    serde_json::json!({})
                };
                match client
                    .put(&url)
                    .header("Content-Type", "application/json")
                    .body(body.to_string())
                    .send()
                    .await
                {
                    Ok(resp) => {
                        let status = resp.status();
                        match resp.text().await {
                            Ok(response_body) => {
                                if status.is_success() {
                                    // Auto-navigate to the new website
                                    if let Some(id) =
                                        serde_json::from_str::<serde_json::Value>(&response_body)
                                            .ok()
                                            .and_then(|v| {
                                                v.get("websiteId")
                                                    .and_then(|id| id.as_str().map(String::from))
                                            })
                                    {
                                        let _ =
                                            self.navigate_to(&format!("{}/?id={}", base_url, id));
                                    }
                                    // Load capabilities synchronously so they're available immediately
                                    match self.load_capabilities().await {
                                        Ok(n) => {
                                            tracing::info!("Loaded {} capabilities after create", n)
                                        }
                                        Err(e) => {
                                            tracing::warn!("Failed to load capabilities: {}", e)
                                        }
                                    }
                                    Ok(CallToolResult::success(vec![Content::text(response_body)]))
                                } else {
                                    Ok(tool_error(format!(
                                        "Error creating website ({}): {}",
                                        status, response_body
                                    )))
                                }
                            }
                            Err(e) => Ok(tool_error(format!("Error reading response: {}", e))),
                        }
                    }
                    Err(e) => Ok(tool_error(format!("Error creating website: {}", e))),
                }
            }

            WebsiteAction::Delete => {
                let wid = params
                    .website_id
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("website_id is required", None))?;
                let url = format!(
                    "{}/api/website?websiteId={}&connectorId=fs-storage",
                    base_url, wid
                );
                match client.delete(&url).send().await {
                    Ok(resp) => {
                        if resp.status().is_success() {
                            let _ = self.navigate_to(&format!("{}/", base_url));
                            // Clear dynamic tools since we're back on dashboard
                            *self.dynamic_tools.write().await = ToolRouter::new();
                            self.capabilities_loaded.store(false, Ordering::Release);
                            Ok(CallToolResult::success(vec![Content::text(format!(
                                "{{\"success\":true,\"message\":\"Website '{}' deleted\"}}",
                                wid
                            ))]))
                        } else {
                            let body = resp.text().await.unwrap_or_default();
                            Ok(tool_error(format!("Error deleting website: {}", body)))
                        }
                    }
                    Err(e) => Ok(tool_error(format!("Error deleting website: {}", e))),
                }
            }

            WebsiteAction::Rename => {
                let wid = params
                    .website_id
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("website_id is required", None))?;
                let name = params
                    .name
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("name is required", None))?;
                let url = format!(
                    "{}/api/website/meta?websiteId={}&connectorId=fs-storage",
                    base_url, wid
                );
                let body = serde_json::json!({ "name": name });
                match client
                    .post(&url)
                    .header("Content-Type", "application/json")
                    .body(body.to_string())
                    .send()
                    .await
                {
                    Ok(resp) => {
                        if resp.status().is_success() {
                            Ok(CallToolResult::success(vec![Content::text(format!(
                                "{{\"success\":true,\"message\":\"Renamed to '{}'\"}}",
                                name
                            ))]))
                        } else {
                            let body = resp.text().await.unwrap_or_default();
                            Ok(tool_error(format!("Error renaming website: {}", body)))
                        }
                    }
                    Err(e) => Ok(tool_error(format!("Error renaming website: {}", e))),
                }
            }

            WebsiteAction::Duplicate => {
                let wid = params
                    .website_id
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("website_id is required", None))?;
                let url = format!(
                    "{}/api/website/duplicate?websiteId={}&connectorId=fs-storage",
                    base_url, wid
                );
                match client.post(&url).send().await {
                    Ok(resp) => {
                        if resp.status().is_success() {
                            let body = resp.text().await.unwrap_or_default();
                            Ok(CallToolResult::success(vec![Content::text(body)]))
                        } else {
                            let body = resp.text().await.unwrap_or_default();
                            Ok(tool_error(format!("Error duplicating website: {}", body)))
                        }
                    }
                    Err(e) => Ok(tool_error(format!("Error duplicating website: {}", e))),
                }
            }

            WebsiteAction::Open => {
                let wid = params
                    .website_id
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("website_id is required", None))?;
                let nav_url = format!("{}/?id={}", base_url, wid);
                match self.navigate_to(&nav_url) {
                    Ok(_) => {
                        // Load capabilities synchronously so they're available immediately
                        match self.load_capabilities().await {
                            Ok(n) => tracing::info!("Loaded {} capabilities after open", n),
                            Err(e) => tracing::warn!("Failed to load capabilities: {}", e),
                        }
                        Ok(CallToolResult::success(vec![Content::text(
                            "{\"success\":true,\"message\":\"Website opened in editor\"}",
                        )]))
                    }
                    Err(e) => Ok(tool_error(e)),
                }
            }

            WebsiteAction::Dashboard => {
                // Clear dynamic tools since we're leaving the editor
                *self.dynamic_tools.write().await = ToolRouter::new();
                self.capabilities_loaded.store(false, Ordering::Release);
                match self.navigate_to(&format!("{}/", base_url)) {
                    Ok(_) => Ok(CallToolResult::success(vec![Content::text(
                        "{\"success\":true,\"message\":\"Navigated to dashboard\"}",
                    )])),
                    Err(e) => Ok(tool_error(e)),
                }
            }
        }
    }

    // ----------------------------------------------------------------------
    // take_screenshot — returns image inline
    // ----------------------------------------------------------------------

    #[tool(
        description = "Take a screenshot and return it as an image. Use target 'canvas' for the website preview only, or 'ui' (default) for the full editor UI including panels. Use this after making visual changes to verify correctness."
    )]
    async fn take_screenshot(
        &self,
        Parameters(params): Parameters<ScreenshotParams>,
    ) -> Result<CallToolResult, McpError> {
        let _tx =
            Self::start_tool_transaction("screenshot", params.target.as_deref().unwrap_or("ui"));
        let target = params.target.as_deref().unwrap_or("ui");

        let screenshot_js = r#"
(async function() {
    if (!window.html2canvas) {
        const s = document.createElement('script');
        s.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js';
        await new Promise((resolve, reject) => {
            s.onload = resolve;
            s.onerror = () => reject(new Error('Failed to load html2canvas from CDN'));
            document.head.appendChild(s);
        });
    }
    let element;
    if ('__TARGET__' === 'canvas') {
        const frame = document.querySelector('.gjs-frame');
        if (frame && frame.contentDocument && frame.contentDocument.body) {
            element = frame.contentDocument.body;
        } else {
            throw new Error('GrapesJS canvas iframe not found or not accessible');
        }
    } else {
        element = document.body;
    }
    const canvas = await html2canvas(element, { useCORS: true, allowTaint: true });
    return canvas.toDataURL('image/png');
})()
"#
        .replace("__TARGET__", target);

        let data_url = match self.eval_js_internal(&screenshot_js, 30).await {
            Ok(Some(url)) => url,
            Ok(None) => return Ok(tool_error("Screenshot returned no data")),
            Err(e) => return Ok(tool_error(format!("Screenshot failed: {}", e))),
        };

        let base64_prefix = "data:image/png;base64,";
        let base64_data = if data_url.starts_with(base64_prefix) {
            &data_url[base64_prefix.len()..]
        } else {
            return Ok(tool_error("Unexpected data URL format"));
        };

        let png_bytes = match base64::engine::general_purpose::STANDARD.decode(base64_data) {
            Ok(bytes) => bytes,
            Err(e) => return Ok(tool_error(format!("Failed to decode base64: {}", e))),
        };

        // Build response with inline image
        let mut content = vec![Content::image(base64_data.to_string(), "image/png")];

        // Optionally save to file
        if let Some(path) = params.output_file {
            match std::fs::write(&path, &png_bytes) {
                Ok(_) => content.push(Content::text(format!("Screenshot also saved to {}", path))),
                Err(e) => content.push(Content::text(format!("Failed to save file: {}", e))),
            }
        }

        Ok(CallToolResult::success(content))
    }
}

// ==========================================================================
// Eval callback handler
// ==========================================================================

pub async fn eval_callback(
    axum::extract::Extension(pending): axum::extract::Extension<PendingEvals>,
    axum::extract::Path(id): axum::extract::Path<u64>,
    body: String,
) -> &'static str {
    if let Some(tx) = held(&pending).remove(&id) {
        let _ = tx.send(body);
    }
    "ok"
}

// ==========================================================================
// ServerHandler — manual impl to merge static + dynamic tools
// ==========================================================================

impl ServerHandler for SilexMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::V_2024_11_05,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation::from_build_env(),
            instructions: Some(
                r#"Silex Desktop MCP — controls the Silex no-code visual website builder.

GETTING STARTED:
1. Call website(action:'list') or website(action:'create', name:'My Site') to start.
2. After opening/creating a project, call list_tools to discover editor tools.
   Editor tools are loaded dynamically and won't appear until a project is open.

HIERARCHY (select each level before operating on deeper levels):
  Website → Breakpoint → Page → Component → Selector
  Every tool response includes a 'selection' object showing the current state, including when the tool fails.
  'warnings' appear only on failed answers, to say what needs to be selected next.

RULES:
- Use BEM class names. No inline styles. No CSS Grid (use Flexbox).
- Homepage page name must be "index". Internal links start with "./".
- Autosave is active — no manual save needed.
- After making visual changes, use take_screenshot to verify your work.
"#
                .into(),
            ),
        }
    }

    fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListToolsResult, McpError>> + Send + '_ {
        async move {
            tracing::info!(
                "[list_tools] Called. caps_loaded={} project_open={}",
                self.capabilities_loaded.load(Ordering::Acquire),
                self.require_project().is_ok()
            );
            // Eagerly load capabilities if a project is open but caps haven't loaded yet
            if !self.capabilities_loaded.load(Ordering::Acquire) && self.require_project().is_ok() {
                tracing::info!("[list_tools] Loading capabilities eagerly...");
                match self.load_capabilities().await {
                    Ok(n) => tracing::info!("[list_tools] Loaded {} capabilities", n),
                    Err(e) => tracing::warn!("[list_tools] Failed to load capabilities: {}", e),
                }
            }
            let mut tools = self.tool_router.list_all();
            // Set annotations on static tools (macro doesn't support them)
            for tool in &mut tools {
                let name = tool.name.as_ref();
                if name == "take_screenshot" {
                    tool.annotations = Some(ToolAnnotations {
                        read_only_hint: Some(true),
                        ..Default::default()
                    });
                }
            }
            let static_count = tools.len();
            // Append dynamic tools from capabilities
            let dynamic = self.dynamic_tools.read().await;
            let dynamic_count = dynamic.list_all().len();
            tools.extend(dynamic.list_all());
            let tool_names: Vec<String> = tools.iter().map(|t| t.name.to_string()).collect();
            tracing::info!(
                "[list_tools] Returning {} tools ({} static + {} dynamic): {:?}",
                tools.len(),
                static_count,
                dynamic_count,
                tool_names
            );
            Ok(ListToolsResult {
                tools,
                next_cursor: None,
                meta: None,
            })
        }
    }

    fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<CallToolResult, McpError>> + Send + '_ {
        async move {
            // Check which router owns this tool before consuming request
            if self.tool_router.get(&request.name).is_some() {
                let is_website_tool = request.name.as_ref() == "website";
                let caps_before = self.capabilities_loaded.load(Ordering::Acquire);
                let peer = context.peer.clone();

                let tool_ctx =
                    rmcp::handler::server::tool::ToolCallContext::new(self, request, context);
                let result = self.tool_router.call(tool_ctx).await;

                // If the website tool just loaded capabilities, notify the client
                if is_website_tool
                    && !caps_before
                    && self.capabilities_loaded.load(Ordering::Acquire)
                {
                    if let Err(e) = peer.notify_tool_list_changed().await {
                        tracing::warn!("Failed to send tools/list_changed: {}", e);
                    }
                }

                return result;
            }

            if self.dynamic_tools.read().await.has_route(&request.name) {
                let tool_ctx =
                    rmcp::handler::server::tool::ToolCallContext::new(self, request, context);
                // Hold read lock across the async call — safe because writes
                // only happen in load_capabilities() on a separate task.
                let dynamic = self.dynamic_tools.read().await;
                return dynamic.call(tool_ctx).await;
            }

            Err(McpError::invalid_params(
                format!(
                    "Tool '{}' not found. Use list_tools to see available tools.",
                    request.name
                ),
                None,
            ))
        }
    }

    fn get_tool(&self, name: &str) -> Option<Tool> {
        self.tool_router
            .get(name)
            .cloned()
            .or_else(|| self.dynamic_tools.try_read().ok()?.get(name).cloned())
    }
}

// ==========================================================================
// Server entry point
// ==========================================================================

/// State shared by every MCP session: the dynamic tools loaded from the page
/// have to survive a session, otherwise they would be lost on website open.
fn shared_state() -> (
    Arc<AtomicU64>,
    Arc<tokio::sync::RwLock<ToolRouter<SilexMcp>>>,
    Arc<std::sync::atomic::AtomicBool>,
) {
    (
        Arc::new(AtomicU64::new(0)),
        Arc::new(tokio::sync::RwLock::new(ToolRouter::new())),
        Arc::new(std::sync::atomic::AtomicBool::new(false)),
    )
}

pub async fn start_mcp_server(
    app_handle: tauri::AppHandle,
    pending_evals: PendingEvals,
    port: u16,
) {
    let (eval_counter, dynamic_tools, capabilities_loaded) = shared_state();

    let mcp_service = StreamableHttpService::new(
        move || {
            Ok(SilexMcp::new(
                app_handle.clone(),
                pending_evals.clone(),
                eval_counter.clone(),
                dynamic_tools.clone(),
                capabilities_loaded.clone(),
            ))
        },
        LocalSessionManager::default().into(),
        Default::default(),
    );

    let router = axum::Router::new().nest_service("/mcp", mcp_service);

    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    let listener = match tokio::net::TcpListener::bind(addr).await {
        Ok(l) => l,
        Err(e) => {
            tracing::warn!("MCP HTTP port {} unavailable ({}), skipping", port, e);
            return;
        }
    };
    let addr = listener.local_addr().unwrap();
    tracing::info!("MCP server listening on http://{}/mcp", addr);

    tokio::spawn(async move {
        axum::serve(listener, router).await.unwrap();
    });
}

pub async fn start_mcp_stdio(app_handle: tauri::AppHandle, pending_evals: PendingEvals) {
    let (eval_counter, dynamic_tools, capabilities_loaded) = shared_state();
    let service = SilexMcp::new(
        app_handle,
        pending_evals,
        eval_counter,
        dynamic_tools,
        capabilities_loaded,
    );
    tracing::info!("MCP stdio transport starting");
    match service.serve(rmcp::transport::io::stdio()).await {
        Ok(server) => {
            let _ = server.waiting().await;
            tracing::info!("MCP stdio transport closed");
        }
        Err(e) => {
            tracing::warn!("MCP stdio not available (launched without stdin?): {}", e);
        }
    }
}

#[cfg(test)]
mod dynamic_tool_answers {
    use super::*;

    #[test]
    fn dynamic_command_js_awaits_run_command_promises() {
        let js = dynamic_command_js("\"fonts:available\"", "\"{}\"");
        assert!(js.contains("await __result__"));
        assert!(js.contains("runCommand"));
        assert!(js.contains("runPublish"));
        assert!(js.contains("fonts:available"));
    }

    #[test]
    fn fonts_available_caps_at_20_and_says_how_many_remain() {
        let fonts: Vec<serde_json::Value> = (0..25)
            .map(|i| serde_json::json!({ "family": format!("Font{i}") }))
            .collect();
        let paged = page_fonts_available(serde_json::json!({ "result": fonts, "selection": {} }));
        assert_eq!(paged["fonts"].as_array().unwrap().len(), 20);
        assert_eq!(paged["remaining"], 5);
        assert!(paged["hint"]
            .as_str()
            .unwrap()
            .contains("5 more fonts available"));
        assert!(paged.get("result").is_none());
        assert!(paged.get("selection").is_some());
    }

    #[test]
    fn fonts_available_has_no_remaining_hint_when_the_page_is_full() {
        let fonts = vec![
            serde_json::json!({ "family": "Roboto" }),
            serde_json::json!({ "family": "Inter" }),
        ];
        let paged = page_fonts_available(serde_json::json!({ "result": fonts }));
        assert_eq!(paged["remaining"], 0);
        assert!(paged.get("hint").is_none());
    }

    #[test]
    fn finish_dynamic_tool_pages_fonts_and_strips_success_warnings() {
        let fonts: Vec<serde_json::Value> = (0..21)
            .map(|i| serde_json::json!({ "family": format!("F{i}") }))
            .collect();
        let (body, is_error) = dynamic_tool_payload(
            "fonts:available",
            serde_json::json!({
                "result": fonts,
                "selection": { "page": "index", "warnings": ["No element selected"] }
            })
            .to_string(),
        );
        assert!(!is_error);
        assert_eq!(body["fonts"].as_array().unwrap().len(), 20);
        assert_eq!(body["remaining"], 1);
        assert!(body["selection"].get("warnings").is_none());
    }

    #[test]
    fn failures_keep_selection_and_warnings() {
        let (body, is_error) = dynamic_tool_payload(
            "styles:set",
            serde_json::json!({
                "error": "Required: property",
                "selection": { "page": "index", "warnings": ["No element selected"] }
            })
            .to_string(),
        );
        assert!(is_error);
        assert_eq!(body["error"], "Required: property");
        assert_eq!(body["selection"]["page"], "index");
        assert_eq!(body["selection"]["warnings"][0], "No element selected");
    }

    #[test]
    fn eval_errors_still_include_selection() {
        let body = dynamic_error_payload(
            "Timeout waiting for JS result (10s)",
            Some(serde_json::json!({ "page": "index" })),
        );
        assert!(body["error"].as_str().unwrap().contains("Timeout"));
        assert_eq!(body["selection"]["page"], "index");
        assert_eq!(finish_dynamic_error("x", None).is_error, Some(true));
    }

    #[test]
    fn publish_pending_and_success_are_not_tool_errors() {
        assert!(!command_is_error(&serde_json::json!({
            "status": "pending",
            "message": "Publication started. Call publish with action status to follow it."
        })));
        assert!(!command_is_error(&serde_json::json!({
            "status": "success",
            "url": "https://example.com"
        })));
        assert!(command_is_error(&serde_json::json!({
            "status": "error",
            "message": "No hosting is set for this website. Ask the user to choose where to publish in the Publish dialog, then retry."
        })));
    }
}
