/*
 * Silex website builder - desktop app.
 * Copyright (c) 2023 lexoyo and Silex Labs foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 */

/*
 * MCP (Model Context Protocol) server for Silex Desktop.
 *
 * Static tools: website, take_screenshot.
 * Dynamic tools: loaded from the grapesjs-ai-capabilities registry
 * after a project is opened. Each capability becomes an MCP tool
 * that calls editor.runCommand() via eval_js.
 */

use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use base64::Engine;
use rmcp::handler::server::router::tool::{ToolRoute, ToolRouter};
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::*;
use rmcp::schemars::JsonSchema;
use rmcp::service::RequestContext;
use rmcp::transport::streamable_http_server::session::local::LocalSessionManager;
use rmcp::transport::streamable_http_server::StreamableHttpService;
use rmcp::{tool, tool_router, ErrorData as McpError, RoleServer, ServerHandler, ServiceExt};
use serde::Deserialize;
use tauri::Manager;
use tokio::sync::oneshot;

use crate::held::held;
use crate::AppState;

// ==========================================================================
// Shared state
// ==========================================================================

/// Pending eval results — shared between MCP tools and the HTTP callback handler.
pub type PendingEvals = Arc<std::sync::Mutex<HashMap<u64, oneshot::Sender<String>>>>;

/// Replaced as a whole when a website opens, so that a running call keeps its own
type DynamicTools = Arc<tokio::sync::RwLock<Arc<ToolRouter<SilexMcp>>>>;

/// Forgets an eval whatever ends the wait: answer, timeout or failure
struct PendingEval<'a> {
    evals: &'a PendingEvals,
    id: u64,
}

impl<'a> PendingEval<'a> {
    fn register(evals: &'a PendingEvals, id: u64) -> (Self, oneshot::Receiver<String>) {
        let (tx, rx) = oneshot::channel::<String>();
        held(evals).insert(id, tx);
        (Self { evals, id }, rx)
    }
}

impl Drop for PendingEval<'_> {
    fn drop(&mut self) {
        held(self.evals).remove(&self.id);
    }
}

// ==========================================================================
// Action enums (static tools only)
// ==========================================================================

#[derive(Debug, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum WebsiteAction {
    List,
    Create,
    Delete,
    Rename,
    Duplicate,
    Open,
    Dashboard,
}

impl WebsiteAction {
    fn changes_tool_list(&self) -> bool {
        matches!(
            self,
            Self::Create | Self::Duplicate | Self::Open | Self::Dashboard | Self::Delete
        )
    }
}

// ==========================================================================
// Parameter structs (static tools only)
// ==========================================================================

#[derive(Debug, Deserialize, JsonSchema)]
pub struct WebsiteParams {
    /// The action to perform.
    pub action: WebsiteAction,
    /// Website ID (required for delete, rename, duplicate, open).
    pub website_id: Option<String>,
    /// Website name (required for create, rename).
    pub name: Option<String>,
}

#[derive(Debug, Default, Clone, Copy, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ScreenshotTarget {
    #[default]
    Ui,
    Canvas,
}

impl ScreenshotTarget {
    fn as_str(self) -> &'static str {
        match self {
            Self::Ui => "ui",
            Self::Canvas => "canvas",
        }
    }
}

#[derive(Debug, Deserialize, JsonSchema)]
pub struct ScreenshotParams {
    /// What to capture: "ui" for the whole editor (default),
    /// or "canvas" for only the website preview.
    pub target: Option<ScreenshotTarget>,
    /// File path to save the screenshot PNG to (optional, also returned inline as image).
    pub output_file: Option<String>,
}

// ==========================================================================
// SilexMcp struct
// ==========================================================================

#[derive(Clone)]
pub struct SilexMcp {
    /// Static tools (website, take_screenshot) generated by #[tool_router].
    tool_router: ToolRouter<Self>,
    /// Dynamic tools loaded from the grapesjs-ai-capabilities JS registry.
    dynamic_tools: DynamicTools,
    /// Whether dynamic capabilities have been loaded for this session.
    capabilities_loaded: Arc<std::sync::atomic::AtomicBool>,
    app_handle: tauri::AppHandle,
    eval_counter: Arc<AtomicU64>,
    pending_evals: PendingEvals,
}

// ==========================================================================
// Internal helpers
// ==========================================================================

impl SilexMcp {
    fn get_base_url(&self) -> String {
        self.app_handle
            .get_webview_window("main")
            .and_then(|w| w.url().ok())
            .map(|u| {
                format!(
                    "{}://{}:{}",
                    u.scheme(),
                    u.host_str().unwrap_or("localhost"),
                    u.port().unwrap_or(6805)
                )
            })
            .unwrap_or_else(|| "http://localhost:6805".to_string())
    }

    /// Navigate the webview to a URL (safe, no injection).
    fn navigate_to(&self, url: &str) -> Result<(), String> {
        let window = self
            .app_handle
            .get_webview_window("main")
            .ok_or_else(|| "No main window".to_string())?;
        let url_json =
            serde_json::to_string(url).map_err(|e| format!("Failed to encode URL: {}", e))?;
        window
            .eval(&format!("window.location.href = {}", url_json))
            .map_err(|e| format!("Navigation failed: {}", e))
    }

    /// A website just made by `create` or `duplicate` opens, as the user would expect
    async fn open_new_website(&self, base_url: &str, id: &str, made: &str) -> CallToolResult {
        let opened = reqwest::Url::parse_with_params(&format!("{}/", base_url), &[("id", id)])
            .map_err(|e| e.to_string())
            .and_then(|url| self.navigate_to(url.as_str()));
        if let Err(e) = opened {
            return tool_error(format!(
                "Website '{}' {} but could not be opened: {}",
                id, made, e
            ));
        }
        match self.load_capabilities().await {
            Ok(n) => tracing::info!("Loaded {} capabilities after the website was {}", n, made),
            Err(e) => tracing::warn!("Failed to load capabilities: {}", e),
        }
        CallToolResult::success(vec![ContentBlock::text(
            serde_json::json!({
                "success": true,
                "websiteId": id,
                "message": format!("Website {} and opened in editor", made),
            })
            .to_string(),
        )])
    }

    /// The dashboard forgets the website only once loaded: until then, the
    /// `list_tools` that follows the notification would poll for editor tools for 30s.
    async fn forget_website(&self) {
        *self.dynamic_tools.write().await = Arc::new(ToolRouter::new());
        self.capabilities_loaded.store(false, Ordering::Release);
        crate::forget_project(&self.app_handle);
    }

    /// Check that a project is open.
    fn require_project(&self) -> Result<(), String> {
        let state = self.app_handle.state::<AppState>();
        if held(&state.current_website_id).is_none() {
            return Err(
                "No project open. Use website(action: 'open') or website(action: 'create') first."
                    .into(),
            );
        }
        Ok(())
    }

    /// Execute JS in the webview and return the result.
    async fn eval_js_internal(
        &self,
        js_code: &str,
        timeout_secs: u64,
    ) -> Result<Option<String>, String> {
        let window = self
            .app_handle
            .get_webview_window("main")
            .ok_or_else(|| "No main window".to_string())?;

        if let Ok(url) = window.url() {
            let path = url.path();
            if path == "/" && url.query().is_none() {
                return Err(
                    "Editor not available — still on dashboard. Open or create a project first."
                        .to_string(),
                );
            }
        }

        let id = self.eval_counter.fetch_add(1, Ordering::Relaxed);
        let (_pending, rx) = PendingEval::register(&self.pending_evals, id);

        // The code goes in the script itself: the editor's CSP refuses eval(),
        // and what Tauri runs here is not subject to it
        let wrapped = r#"(async()=>{try{let __r=(__JS__
);if(__r instanceof Promise)__r=await __r;const __s=(typeof __r==='undefined')?null:(typeof __r==='string')?__r:JSON.stringify(__r);await fetch(window.location.origin+'/eval-callback/__ID__',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({success:true,result:__s})})}catch(__e){await fetch(window.location.origin+'/eval-callback/__ID__',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({success:false,error:__e.message||String(__e)})})}})()"#
            .replace("__ID__", &id.to_string())
            .replace("__JS__", js_code);

        window
            .eval(&wrapped)
            .map_err(|e| format!("Failed to inject JS: {}", e))?;

        let raw = tokio::time::timeout(std::time::Duration::from_secs(timeout_secs), rx)
            .await
            .map_err(|_| format!("The editor did not answer within {timeout_secs}s."))?
            .map_err(|_| {
                "Internal error: JS callback channel closed unexpectedly. Retry the operation."
                    .to_string()
            })?;

        #[derive(Deserialize)]
        struct JsResult {
            success: bool,
            result: Option<String>,
            error: Option<String>,
        }

        let parsed: JsResult =
            serde_json::from_str(&raw).map_err(|e| format!("Failed to parse JS result: {}", e))?;

        if parsed.success {
            Ok(parsed.result)
        } else {
            Err(parsed.error.unwrap_or_else(|| "Unknown JS error".into()))
        }
    }

    // ======================================================================
    // Dynamic capability loading
    // ======================================================================

    /// Load capabilities from the editor's JS registry and add as dynamic MCP tools.
    /// Called after a website is opened/created and the editor is ready.
    async fn load_capabilities(&self) -> Result<usize, String> {
        // Wait for capabilities to be registered (poll up to 30s).
        // The registry function exists early, but capabilities are registered
        // after the editor 'load' event fires 'ai-capabilities:ready'.
        // So we poll until getAllCapabilities() returns a non-empty array.
        let mut raw = "[]".to_string();
        let mut ready = false;
        for _ in 0..60 {
            let js = "JSON.stringify(window.__silexMcp?.getCapabilities?.() || [])";
            match self.eval_js_internal(js, 3).await {
                Ok(Some(val)) if val != "[]" && val.len() > 2 => {
                    raw = val;
                    ready = true;
                    break;
                }
                _ => {}
            }
            tokio::time::sleep(std::time::Duration::from_millis(500)).await;
        }
        if !ready {
            return Err("Editor capabilities not available after 30s".into());
        }

        #[derive(Deserialize)]
        struct CapDef {
            id: String,
            command: String,
            description: String,
            #[serde(rename = "inputSchema", default)]
            input_schema: Option<serde_json::Value>,
            #[serde(rename = "readOnly", default)]
            read_only: Option<bool>,
            #[serde(default)]
            destructive: Option<bool>,
            #[serde(default)]
            idempotent: Option<bool>,
            #[serde(rename = "openWorld", default)]
            open_world: Option<bool>,
        }

        let caps: Vec<CapDef> = serde_json::from_str(&raw)
            .map_err(|e| format!("Failed to parse capabilities: {}", e))?;

        let count = caps.len();
        let mut router = ToolRouter::new();

        for cap in caps {
            // Build the JSON Schema for the tool's input.
            // Ensure schema always has "type": "object" — some MCP clients
            // reject tools without a valid JSON Schema.
            let default_schema = serde_json::json!({"type": "object", "properties": {}});
            let schema_value = match cap.input_schema {
                Some(serde_json::Value::Object(ref m)) if m.contains_key("type") => {
                    cap.input_schema.unwrap()
                }
                _ => default_schema,
            };

            // Convert Value to JsonObject and sanitize property keys
            // (MCP clients require keys to match ^[a-zA-Z0-9_.-]{1,64})
            let schema_obj = match schema_value {
                serde_json::Value::Object(mut map) => {
                    if let Some(serde_json::Value::Object(props)) = map.remove("properties") {
                        let sanitized: serde_json::Map<String, serde_json::Value> = props
                            .into_iter()
                            .map(|(k, v)| (k.replace(':', "_"), v))
                            .collect();
                        map.insert("properties".into(), serde_json::Value::Object(sanitized));
                    }
                    map
                }
                _ => serde_json::Map::new(),
            };

            let mut annotations = ToolAnnotations::new();
            annotations.read_only_hint = cap.read_only.or(Some(false));
            annotations.destructive_hint = if cap.read_only == Some(true) {
                None
            } else {
                cap.destructive.or(Some(false))
            };
            annotations.idempotent_hint = cap.idempotent;
            annotations.open_world_hint = cap.open_world;

            // ':' in capability ids is not allowed in tool names (clients require ^[a-zA-Z0-9_-]+$)
            let tool = Tool::new(
                cap.id.replace(':', "_"),
                cap.description,
                Arc::new(schema_obj),
            )
            .with_annotations(annotations);

            let cap_command = Arc::new(cap.command);
            // A command that queries a remote server (a CMS schema) can take far more than 10 s
            let timeout_secs = if cap.open_world == Some(true) { 45 } else { 10 };

            let route = ToolRoute::new_dyn(tool, move |ctx| {
                let cmd = cap_command.clone();
                Box::pin(async move {
                    let mcp: &SilexMcp = ctx.service;

                    // Get params as JSON object
                    let params_json = ctx
                        .arguments
                        .as_ref()
                        .map(|v| serde_json::Value::Object(v.clone()).to_string())
                        .unwrap_or_else(|| "{}".into());

                    let cmd_js = serde_json::to_string(cmd.as_str()).unwrap();
                    let params_js_escaped = serde_json::to_string(&params_json).unwrap();

                    let js = COMMAND_JS
                        .replace("__CMD__", &cmd_js)
                        .replace("__PARAMS__", &params_js_escaped);

                    mcp.require_project()
                        .map_err(|e| McpError::internal_error(e, None))?;
                    let state = mcp.app_handle.state::<AppState>();
                    // A call cancelled while it waits for its turn must not run later
                    let _one_at_a_time = tokio::select! {
                        guard = state.editor_commands.lock() => guard,
                        _ = ctx.request_context.ct.cancelled() => {
                            return Err(McpError::internal_error("The call was cancelled before it ran", None));
                        }
                    };
                    // Kept until the editor answers even if the call is cancelled: the
                    // command goes on running there
                    match mcp.eval_js_internal(&js, timeout_secs).await {
                        Ok(result) => {
                            let text = result.unwrap_or_else(|| "null".into());
                            let is_error = serde_json::from_str::<serde_json::Value>(&text)
                                .ok()
                                .map(|v| {
                                    v.get("error").map_or(false, |e| !e.is_null())
                                        || v.get("success").map_or(false, |s| s == false)
                                })
                                .unwrap_or(false);
                            let content = vec![ContentBlock::text(text)];
                            Ok(if is_error {
                                CallToolResult::error(content)
                            } else {
                                CallToolResult::success(content)
                            }
                            .into())
                        }
                        Err(e) => Ok(tool_error(e).into()),
                    }
                })
            });

            router.add_route(route);
        }

        // Replace the dynamic tools router
        *self.dynamic_tools.write().await = Arc::new(router);
        self.capabilities_loaded.store(true, Ordering::Release);

        tracing::info!("Loaded {} dynamic capabilities as MCP tools", count);
        Ok(count)
    }
}

/// The selection comes with the answer only when it changed or the command failed:
/// repeated on every call, it was most of what the tools returned. Its selector
/// comes from selector:get, the style panel follows the selection only later.
/// Elements and pages are named by the ids the tools take. A text answer stays
/// text, with the selection on a last line.
const COMMAND_JS: &str = r#"(async function(){
var e=window.silex.getEditor();
var selection=function(){
  var s=window.__silexMcp.getSelectionState(e);
  delete s.warnings;
  var page=e.Pages.getSelected(),element=e.getSelected();
  s.page=page?page.id:null;
  s.component=element?e.runCommand('agent-ids:get',{component:element}):null;
  s.selector=null;
  if(s.component&&e.Commands.has('selector:get'))s.selector=e.runCommand('selector:get').selector;
  return s;
};
var before=JSON.stringify(selection());
var result;
try{result=await e.runCommand(__CMD__,JSON.parse(__PARAMS__))}
catch(ex){
  var failed={error:ex.message||String(ex)};
  try{failed.selection=selection()}catch(ex2){console.error(ex2)}
  return JSON.stringify(failed);
}
if(typeof result==='undefined'||result===null)result={};
var after=selection();
var changed=JSON.stringify(after)!==before;
if(typeof result==='string'){try{result=JSON.parse(result)}catch(_){return changed?result+'\nselection: '+JSON.stringify(after):result}}
if(Array.isArray(result)||typeof result!=='object'||result===null)result={result:result};
if(result.error||result.success===false||changed)result.selection=after;
return JSON.stringify(result);
})()"#;

/// The id the server gives a website it just made
fn new_website_id(body: &str) -> Option<String> {
    #[derive(Deserialize)]
    #[serde(rename_all = "camelCase")]
    struct NewWebsite {
        website_id: String,
    }
    serde_json::from_str::<NewWebsite>(body)
        .ok()
        .map(|made| made.website_id)
}

/// Create an error CallToolResult (is_error = true).
fn tool_error(msg: impl Into<String>) -> CallToolResult {
    CallToolResult::error(vec![ContentBlock::text(msg.into())])
}

// ==========================================================================
// Static tool implementations
// ==========================================================================

/// Sentry puts no Drop on its own spans, and one that is never finished is
/// never sent
struct ToolSpan {
    span: Option<sentry::TransactionOrSpan>,
    answered: bool,
}

impl ToolSpan {
    /// One per tool call, with only values chosen by Silex: never the arguments,
    /// an error message, nor anything else of the website
    fn start(tool: &str, action: Option<&str>, client: Option<&str>) -> Self {
        let tx_ctx = sentry::TransactionContext::new(&format!("mcp/{}", tool), "mcp.tool");
        let transaction = sentry::start_transaction(tx_ctx);
        if let Some(action) = action {
            transaction.set_tag("action", action);
        }
        if let Some(client) = client {
            transaction.set_tag("client", client.chars().take(64).collect::<String>());
        }
        Self {
            span: Some(transaction.into()),
            answered: false,
        }
    }

    fn answers(&mut self, result: &Result<CallToolResponse, McpError>) {
        self.answered = true;
        let Some(span) = &self.span else { return };
        let outcome = match result {
            Ok(CallToolResponse::Complete(call)) => {
                let bytes: usize = call
                    .content
                    .iter()
                    .map(|block| {
                        block
                            .as_text()
                            .map(|text| text.text.len())
                            .unwrap_or_default()
                            + block
                                .as_image()
                                .map(|image| image.data.len())
                                .unwrap_or_default()
                    })
                    .sum();
                span.set_data("response_bytes", bytes.into());
                if call.is_error == Some(true) {
                    "tool_error"
                } else {
                    "ok"
                }
            }
            Ok(CallToolResponse::InputRequired(_)) => "input_required",
            Ok(_) => "task",
            Err(e) => {
                span.set_data("error_code", e.code.0.into());
                "protocol_error"
            }
        };
        span.set_tag("outcome", outcome);
        if matches!(outcome, "tool_error" | "protocol_error") {
            span.set_status(sentry::protocol::SpanStatus::InternalError);
        }
    }
}

impl Drop for ToolSpan {
    fn drop(&mut self) {
        if let Some(span) = self.span.take() {
            if !self.answered {
                span.set_tag("outcome", "cancelled");
                span.set_status(sentry::protocol::SpanStatus::Cancelled);
            }
            span.finish();
        }
    }
}

#[tool_router]
impl SilexMcp {
    pub fn new(
        app_handle: tauri::AppHandle,
        pending_evals: PendingEvals,
        eval_counter: Arc<AtomicU64>,
        dynamic_tools: DynamicTools,
        capabilities_loaded: Arc<std::sync::atomic::AtomicBool>,
    ) -> Self {
        Self {
            tool_router: Self::tool_router(),
            dynamic_tools,
            capabilities_loaded,
            app_handle,
            eval_counter,
            pending_evals,
        }
    }

    // ----------------------------------------------------------------------
    // website — list, create, delete, rename, duplicate, open, dashboard
    // ----------------------------------------------------------------------

    #[tool(
        description = "Manage websites in the Silex visual website builder. Actions: list, create, delete, rename, duplicate, open, dashboard. After create, duplicate or open, the editor tools are added to the tool list. Use dashboard to return to the website list."
    )]
    async fn website(
        &self,
        Parameters(params): Parameters<WebsiteParams>,
    ) -> Result<CallToolResult, McpError> {
        let base_url = self.get_base_url();
        let client = reqwest::Client::new();

        match params.action {
            WebsiteAction::List => {
                let url = format!("{}/api/website", base_url);
                match reqwest::get(&url).await {
                    Ok(resp) => match resp.text().await {
                        Ok(body) => Ok(CallToolResult::success(vec![ContentBlock::text(body)])),
                        Err(e) => Ok(tool_error(format!("Error reading response: {}", e))),
                    },
                    Err(e) => Ok(tool_error(format!("Error fetching websites: {}", e))),
                }
            }

            WebsiteAction::Create => {
                let url = format!("{}/api/website?connectorId=fs-storage", base_url);
                let body = if let Some(name) = &params.name {
                    serde_json::json!({ "name": name })
                } else {
                    serde_json::json!({})
                };
                match client
                    .put(&url)
                    .header("Content-Type", "application/json")
                    .body(body.to_string())
                    .send()
                    .await
                {
                    Ok(resp) => {
                        let status = resp.status();
                        match resp.text().await {
                            Ok(response_body) => {
                                if status.is_success() {
                                    let Some(id) = new_website_id(&response_body) else {
                                        return Ok(tool_error(format!(
                                            "Website created but the server sent no websiteId, so it was not opened. Do not create it again, find it with website(action:'list'): {}",
                                            response_body
                                        )));
                                    };
                                    Ok(self.open_new_website(&base_url, &id, "created").await)
                                } else {
                                    Ok(tool_error(format!(
                                        "Error creating website ({}): {}",
                                        status, response_body
                                    )))
                                }
                            }
                            Err(e) => Ok(tool_error(format!("Error reading response: {}", e))),
                        }
                    }
                    Err(e) => Ok(tool_error(format!("Error creating website: {}", e))),
                }
            }

            WebsiteAction::Delete => {
                let wid = params
                    .website_id
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("website_id is required", None))?;
                let url = format!(
                    "{}/api/website?websiteId={}&connectorId=fs-storage",
                    base_url, wid
                );
                match client.delete(&url).send().await {
                    Ok(resp) => {
                        if resp.status().is_success() {
                            let was_open =
                                held(&self.app_handle.state::<AppState>().current_website_id)
                                    .as_deref()
                                    == Some(wid);
                            if was_open && self.navigate_to(&format!("{}/", base_url)).is_ok() {
                                self.forget_website().await;
                            }
                            Ok(CallToolResult::success(vec![ContentBlock::text(format!(
                                "{{\"success\":true,\"message\":\"Website '{}' deleted\"}}",
                                wid
                            ))]))
                        } else {
                            let body = resp.text().await.unwrap_or_default();
                            Ok(tool_error(format!("Error deleting website: {}", body)))
                        }
                    }
                    Err(e) => Ok(tool_error(format!("Error deleting website: {}", e))),
                }
            }

            WebsiteAction::Rename => {
                let wid = params
                    .website_id
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("website_id is required", None))?;
                let name = params
                    .name
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("name is required", None))?;
                let url = format!(
                    "{}/api/website/meta?websiteId={}&connectorId=fs-storage",
                    base_url, wid
                );
                let body = serde_json::json!({ "name": name });
                match client
                    .post(&url)
                    .header("Content-Type", "application/json")
                    .body(body.to_string())
                    .send()
                    .await
                {
                    Ok(resp) => {
                        if resp.status().is_success() {
                            Ok(CallToolResult::success(vec![ContentBlock::text(format!(
                                "{{\"success\":true,\"message\":\"Renamed to '{}'\"}}",
                                name
                            ))]))
                        } else {
                            let body = resp.text().await.unwrap_or_default();
                            Ok(tool_error(format!("Error renaming website: {}", body)))
                        }
                    }
                    Err(e) => Ok(tool_error(format!("Error renaming website: {}", e))),
                }
            }

            WebsiteAction::Duplicate => {
                let wid = params
                    .website_id
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("website_id is required", None))?;
                let url = format!(
                    "{}/api/website/duplicate?websiteId={}&connectorId=fs-storage",
                    base_url, wid
                );
                match client.post(&url).send().await {
                    Ok(resp) => {
                        let status = resp.status();
                        match resp.text().await {
                            Ok(body) if status.is_success() => {
                                let Some(copy_id) = new_website_id(&body) else {
                                    return Ok(tool_error(format!(
                                        "Website duplicated but the server sent no websiteId, so the copy was not opened. Do not duplicate it again, find it with website(action:'list'): {}",
                                        body
                                    )));
                                };
                                Ok(self
                                    .open_new_website(&base_url, &copy_id, "duplicated")
                                    .await)
                            }
                            Ok(body) => Ok(tool_error(format!(
                                "Error duplicating website ({}): {}",
                                status, body
                            ))),
                            Err(e) => Ok(tool_error(format!("Error reading response: {}", e))),
                        }
                    }
                    Err(e) => Ok(tool_error(format!("Error duplicating website: {}", e))),
                }
            }

            WebsiteAction::Open => {
                let wid = params
                    .website_id
                    .as_deref()
                    .ok_or_else(|| McpError::invalid_params("website_id is required", None))?;
                let nav_url = format!("{}/?id={}", base_url, wid);
                match self.navigate_to(&nav_url) {
                    Ok(_) => {
                        // Load capabilities synchronously so they're available immediately
                        match self.load_capabilities().await {
                            Ok(n) => tracing::info!("Loaded {} capabilities after open", n),
                            Err(e) => tracing::warn!("Failed to load capabilities: {}", e),
                        }
                        Ok(CallToolResult::success(vec![ContentBlock::text(
                            "{\"success\":true,\"message\":\"Website opened in editor\"}",
                        )]))
                    }
                    Err(e) => Ok(tool_error(e)),
                }
            }

            WebsiteAction::Dashboard => match self.navigate_to(&format!("{}/", base_url)) {
                Ok(_) => {
                    self.forget_website().await;
                    Ok(CallToolResult::success(vec![ContentBlock::text(
                        "{\"success\":true,\"message\":\"Navigated to dashboard\"}",
                    )]))
                }
                Err(e) => Ok(tool_error(e)),
            },
        }
    }

    // ----------------------------------------------------------------------
    // take_screenshot — returns image inline
    // ----------------------------------------------------------------------

    #[tool(
        description = "Take a screenshot and return it as an image. Use target 'canvas' for the website preview only, or 'ui' (default) for the full editor UI including panels. Use this after making visual changes to verify correctness."
    )]
    async fn take_screenshot(
        &self,
        Parameters(params): Parameters<ScreenshotParams>,
    ) -> Result<CallToolResult, McpError> {
        let state = self.app_handle.state::<AppState>();
        let _after_the_writes = state.editor_commands.lock().await;
        let target = params.target.unwrap_or_default().as_str();
        let Some(html2canvas) = crate::frontend::html2canvas() else {
            return Ok(tool_error(
                "Screenshot failed: html2canvas is not in the dashboard build",
            ));
        };
        let html2canvas = serde_json::to_string(&html2canvas).unwrap_or_default();

        let screenshot_js = r#"
(async function() {
    const { default: html2canvas } = await import(__HTML2CANVAS__);
    let element;
    if ('__TARGET__' === 'canvas') {
        const frame = document.querySelector('.gjs-frame');
        if (frame && frame.contentDocument && frame.contentDocument.body) {
            element = frame.contentDocument.body;
        } else {
            throw new Error('GrapesJS canvas iframe not found or not accessible');
        }
    } else {
        element = document.body;
    }
    const canvas = await html2canvas(element, { useCORS: true, allowTaint: true });
    return canvas.toDataURL('image/png');
})()
"#
        .replace("__TARGET__", target)
        .replace("__HTML2CANVAS__", &html2canvas);

        let data_url = match self.eval_js_internal(&screenshot_js, 30).await {
            Ok(Some(url)) => url,
            Ok(None) => return Ok(tool_error("Screenshot returned no data")),
            Err(e) => return Ok(tool_error(format!("Screenshot failed: {}", e))),
        };

        let base64_prefix = "data:image/png;base64,";
        let base64_data = if data_url.starts_with(base64_prefix) {
            &data_url[base64_prefix.len()..]
        } else {
            return Ok(tool_error("Unexpected data URL format"));
        };

        let png_bytes = match base64::engine::general_purpose::STANDARD.decode(base64_data) {
            Ok(bytes) => bytes,
            Err(e) => return Ok(tool_error(format!("Failed to decode base64: {}", e))),
        };

        // Build response with inline image
        let mut content = vec![ContentBlock::image(base64_data.to_string(), "image/png")];

        // Optionally save to file
        if let Some(path) = params.output_file {
            match std::fs::write(&path, &png_bytes) {
                Ok(_) => content.push(ContentBlock::text(format!(
                    "Screenshot also saved to {}",
                    path
                ))),
                Err(e) => content.push(ContentBlock::text(format!("Failed to save file: {}", e))),
            }
        }

        Ok(CallToolResult::success(content))
    }
}

// ==========================================================================
// Eval callback handler
// ==========================================================================

pub async fn eval_callback(
    axum::extract::Extension(pending): axum::extract::Extension<PendingEvals>,
    axum::extract::Path(id): axum::extract::Path<u64>,
    body: String,
) -> &'static str {
    if let Some(tx) = held(&pending).remove(&id) {
        let _ = tx.send(body);
    }
    "ok"
}

// ==========================================================================
// ServerHandler — manual impl to merge static + dynamic tools
// ==========================================================================

impl ServerHandler for SilexMcp {
    fn get_info(&self) -> ServerConfig {
        ServerConfig::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_tool_list_changed()
                .build(),
        )
        .with_protocol_version(ProtocolVersion::V_2024_11_05)
        .with_instructions(
            r#"Silex Desktop MCP: controls Silex, a visual website builder.

GETTING STARTED:
1. Call website(action:'list') or website(action:'create', name:'My Site') to start.
2. The editor tools (pages, components, styles...) appear once a website is open.

SELECTION: website > page > element > selector. Choose each level before the next one.
Screen size: device_set chooses it ("breakpoint" in the selection). Styles apply to that screen size only.
An answer shows the selection (a "selection" object, or a last line "selection: ..." after a text answer) only when it changed or the call failed.

TO STYLE: components_select an element, selector_set a selector that matches it (for a new class, call classes_add first), then one styles_set with all the CSS.

CMS: cms(action:'add', source:'wp', url:'https://.../graphql') tests and connects a GraphQL API (WordPress headless...) and lists its collections. To repeat a card: keep one card, components_remove its copies, components_select the card, cms(action:'bind', bind_to:'loop', path:'wp.posts(first: 3).nodes'); the answer lists the item fields. Then for each child: components_select it, cms(action:'bind', bind_to:'content', path:'item.title'), or cms(action:'bind', bind_to:'attribute', attribute:'href', path:'item.link').

IDS: tools that create return the new ids in "created": use them, no need for components_list. blocks_add, symbols_create, pages_add and pages_clone also select what they create when it is one element or page. Element ids change when the website is reopened.

RULES:
- Use BEM class names. No inline styles. No CSS Grid (use Flexbox).
- The page with no name is the homepage. Internal links start with "./".
- Autosave is active — no manual save needed.
- After making visual changes, use take_screenshot to verify your work.
"#,
        )
    }

    fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<ListToolsResult, McpError>> + Send + '_ {
        async move {
            tracing::info!(
                "[list_tools] Called. caps_loaded={} project_open={}",
                self.capabilities_loaded.load(Ordering::Acquire),
                self.require_project().is_ok()
            );
            // Eagerly load capabilities if a project is open but caps haven't loaded yet
            if !self.capabilities_loaded.load(Ordering::Acquire) && self.require_project().is_ok() {
                tracing::info!("[list_tools] Loading capabilities eagerly...");
                match self.load_capabilities().await {
                    Ok(n) => tracing::info!("[list_tools] Loaded {} capabilities", n),
                    Err(e) => tracing::warn!("[list_tools] Failed to load capabilities: {}", e),
                }
            }
            let mut tools = self.tool_router.list_all();
            // Set annotations on static tools (macro doesn't support them)
            for tool in &mut tools {
                let name = tool.name.as_ref();
                if name == "take_screenshot" {
                    tool.annotations = Some(ToolAnnotations::new().read_only(true));
                }
            }
            let static_count = tools.len();
            // Append dynamic tools from capabilities
            let dynamic = self.dynamic_tools.read().await;
            let dynamic_count = dynamic.list_all().len();
            tools.extend(dynamic.list_all());
            let tool_names: Vec<String> = tools.iter().map(|t| t.name.to_string()).collect();
            tracing::info!(
                "[list_tools] Returning {} tools ({} static + {} dynamic): {:?}",
                tools.len(),
                static_count,
                dynamic_count,
                tool_names
            );
            Ok(ListToolsResult::with_all_items(tools))
        }
    }

    fn call_tool(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = Result<CallToolResponse, McpError>> + Send + '_ {
        async move {
            let known = self.get_tool(&request.name);
            let tool = known.as_ref().map_or("unknown", |tool| tool.name.as_ref());
            let action = known.as_ref().and_then(|tool| known_action(tool, &request));
            let client = context
                .peer
                .peer_info()
                .map(|info| info.client_info.name.clone());
            let mut span = ToolSpan::start(tool, action.as_deref(), client.as_deref());
            let result = self.route_call(request, context).await;
            span.answers(&result);
            result
        }
    }

    fn get_tool(&self, name: &str) -> Option<Tool> {
        self.tool_router
            .get(name)
            .cloned()
            .or_else(|| self.dynamic_tools.try_read().ok()?.get(name).cloned())
    }
}

impl SilexMcp {
    async fn route_call(
        &self,
        request: CallToolRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<CallToolResponse, McpError> {
        // Check which router owns this tool before consuming request
        if self.tool_router.get(&request.name).is_some() {
            let may_change_tool_list = request.name.as_ref() == "website"
                && request
                    .arguments
                    .as_ref()
                    .and_then(|args| args.get("action"))
                    .and_then(|action| serde_json::from_value::<WebsiteAction>(action.clone()).ok())
                    .is_some_and(|action| action.changes_tool_list());
            let peer = context.peer.clone();

            let tool_ctx =
                rmcp::handler::server::tool::ToolCallContext::new(self, request, context);
            let result = self.tool_router.call(tool_ctx).await;

            let succeeded = matches!(
                &result,
                Ok(CallToolResponse::Complete(done)) if done.is_error != Some(true)
            );
            if may_change_tool_list && succeeded {
                if let Err(e) = peer.notify_tool_list_changed().await {
                    tracing::warn!("Failed to send tools/list_changed: {}", e);
                }
            }

            return result;
        }

        // Not under the lock: a long call would keep load_capabilities waiting
        let dynamic = {
            let tools = self.dynamic_tools.read().await;
            tools.has_route(&request.name).then(|| Arc::clone(&tools))
        };
        if let Some(dynamic) = dynamic {
            let tool_ctx =
                rmcp::handler::server::tool::ToolCallContext::new(self, request, context);
            return dynamic.call(tool_ctx).await;
        }

        Err(McpError::invalid_params(
            format!(
                "Tool '{}' not found. The editor tools are only available while a website is open.",
                request.name
            ),
            None,
        ))
    }
}

/// The action of a call, when it is one the tool declares: a free value could
/// be anything of the website
fn known_action(tool: &Tool, request: &CallToolRequestParams) -> Option<String> {
    let args = request.arguments.as_ref()?;
    match tool.name.as_ref() {
        "website" => {
            let action = args.get("action")?;
            serde_json::from_value::<WebsiteAction>(action.clone()).ok()?;
            action.as_str().map(String::from)
        }
        "take_screenshot" => {
            let target = args.get("target").cloned().unwrap_or_default();
            let target = if target.is_null() {
                ScreenshotTarget::default()
            } else {
                serde_json::from_value::<ScreenshotTarget>(target).ok()?
            };
            Some(target.as_str().to_string())
        }
        _ => {
            let action = args.get("action")?.as_str()?;
            tool.input_schema
                .get("properties")?
                .get("action")?
                .get("enum")?
                .as_array()?
                .iter()
                .any(|allowed| allowed.as_str() == Some(action))
                .then(|| action.to_string())
        }
    }
}

// ==========================================================================
// Server entry point
// ==========================================================================

/// State shared by every MCP session: the dynamic tools loaded from the page
/// have to survive a session, otherwise they would be lost on website open.
fn shared_state() -> (
    Arc<AtomicU64>,
    DynamicTools,
    Arc<std::sync::atomic::AtomicBool>,
) {
    (
        Arc::new(AtomicU64::new(0)),
        Arc::new(tokio::sync::RwLock::new(Arc::new(ToolRouter::new()))),
        Arc::new(std::sync::atomic::AtomicBool::new(false)),
    )
}

pub async fn start_mcp_server(
    app_handle: tauri::AppHandle,
    pending_evals: PendingEvals,
    port: u16,
) {
    let (eval_counter, dynamic_tools, capabilities_loaded) = shared_state();

    let mcp_service = StreamableHttpService::new(
        move || {
            Ok(SilexMcp::new(
                app_handle.clone(),
                pending_evals.clone(),
                eval_counter.clone(),
                dynamic_tools.clone(),
                capabilities_loaded.clone(),
            ))
        },
        LocalSessionManager::default().into(),
        Default::default(),
    );

    let router = axum::Router::new().nest_service("/mcp", mcp_service);

    let addr = std::net::SocketAddr::from(([127, 0, 0, 1], port));
    let listener = match tokio::net::TcpListener::bind(addr).await {
        Ok(l) => l,
        Err(e) => {
            tracing::warn!("MCP HTTP port {} unavailable ({}), skipping", port, e);
            return;
        }
    };
    let addr = listener.local_addr().unwrap();
    tracing::info!("MCP server listening on http://{}/mcp", addr);

    tokio::spawn(async move {
        axum::serve(listener, router).await.unwrap();
    });
}

pub async fn start_mcp_stdio(app_handle: tauri::AppHandle, pending_evals: PendingEvals) {
    let (eval_counter, dynamic_tools, capabilities_loaded) = shared_state();
    let service = SilexMcp::new(
        app_handle,
        pending_evals,
        eval_counter,
        dynamic_tools,
        capabilities_loaded,
    );
    tracing::info!("MCP stdio transport starting");
    match service.serve(rmcp::transport::io::stdio()).await {
        Ok(server) => {
            let _ = server.waiting().await;
            tracing::info!("MCP stdio transport closed");
        }
        Err(e) => {
            tracing::warn!("MCP stdio not available (launched without stdin?): {}", e);
        }
    }
}
