/*
 * Silex website builder, free/libre no-code tool for makers.
 * Copyright (c) 2023 lexoyo and Silex Labs foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 */

//! Publication API routes
//!
//! Route:
//! - POST /api/publication/?websiteId=X - Publish the website
//!
//! The editor generates the files and sends them here. Publishing to the local
//! filesystem is done by the time the response is sent, so there is no job to
//! poll: the HTTP status is the result. On the SaaS, where publishing means
//! pushing to a forge and waiting for a build, the server answers a job and the
//! editor polls it.

use axum::extract::{Query, State};
use axum::routing::post;
use axum::{Json, Router};
use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};
use crate::models::{File, WebsiteId};
use crate::publish;
use crate::routes::AppState;
use crate::storage;

/// Build publication routes
pub fn routes() -> Router<AppState> {
    Router::new().route("/", post(publish_website))
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PublishQuery {
    pub website_id: WebsiteId,
}

/// Publication request body
///
/// The editor also sends the website data and the publication options, which
/// only a hosting service could use. Serde ignores them.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PublishRequest {
    #[serde(default)]
    pub files: Vec<ClientSideFile>,
}

/// A file generated by the editor
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientSideFile {
    /// Path where the file is published
    pub path: String,

    /// File content, for the files the editor generates
    #[serde(default)]
    pub content: Option<String>,

    /// Path of a stored asset, for the files the editor references
    #[serde(default)]
    pub src: Option<String>,
}

/// The editor logs the URL and drops it. A published folder has no URL until
/// something serves it, which is the desktop app's business.
#[derive(Debug, Serialize)]
pub struct PublishResponse {
    pub url: Option<String>,
}

/// Publish a website
///
/// POST /api/publication/?websiteId=X
async fn publish_website(
    State(state): State<AppState>,
    Query(query): Query<PublishQuery>,
    Json(request): Json<PublishRequest>,
) -> Result<Json<PublishResponse>> {
    let mut files: Vec<File> = Vec::new();

    for file in request.files {
        let content = match (file.content, file.src) {
            (Some(content), _) => content.into_bytes(),
            (None, Some(src)) => {
                let asset_name = asset_name_of(&src);
                storage::read_asset(&state.data_path, &query.website_id, &asset_name).await?
            }
            (None, None) => {
                return Err(Error::InvalidInput(format!(
                    "File '{}' has neither content nor src",
                    file.path
                )))
            }
        };

        files.push(File {
            path: file.path,
            content,
        });
    }

    publish::publish(&state.data_path, &query.website_id, &files).await?;

    Ok(Json(PublishResponse { url: None }))
}

/// Asset name out of the `src` sent by the editor
///
/// The editor is expected to send a stored path, but it has been seen sending
/// an API path or a full URL. Logged so that we can tell what it really sends
/// and drop this if it turns out to be dead weight.
fn asset_name_of(src: &str) -> String {
    tracing::debug!(src = %src, "publish: reading asset");

    if let Some(pos) = src.find("/api/website/assets/") {
        let after = &src[pos + "/api/website/assets/".len()..];
        return after.split('?').next().unwrap_or(after).to_string();
    }

    if let Some(stripped) = src.strip_prefix("/assets/") {
        return stripped.to_string();
    }

    src.to_string()
}
