/*
 * Silex website builder, free/libre no-code tool for makers.
 * Copyright (c) 2023 lexoyo and Silex Labs foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 */

//! Publication API routes
//!
//! Routes:
//! - POST /api/publication/?websiteId=X - Publish the website
//! - GET /api/publication/publication/status?jobId=X - Where that publication is
//!
//! The editor generates the files and sends them here. Writing them is quick;
//! what a host application then does with them - sending them to a forge,
//! waiting for that forge to build them - is not, and an HTTP request held open
//! for minutes is one a proxy or a laptop lid closes. So publishing answers a
//! job straight away and the editor asks about it every couple of seconds,
//! which is the contract it was written against on the hosted version.
//!
//! The doubled path of the status route is not a mistake: the editor builds it
//! out of `/publication` and `/publication/status`, and the hosted server
//! answers it there too.

use axum::extract::{Query, State};
use axum::routing::{get, post};
use axum::{Json, Router};
use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};
use crate::jobs::{JobData, JobStatus};
use crate::models::{File, WebsiteId};
use crate::publish;
use crate::routes::AppState;
use crate::storage;

/// Build publication routes
pub fn routes() -> Router<AppState> {
    Router::new()
        .route("/", post(publish_website))
        .route("/publication/status", get(publication_status))
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PublishQuery {
    pub website_id: WebsiteId,

    /// The publication options, as JSON
    ///
    /// The editor puts everything that is not a string in the query encoded
    /// that way, so this arrives as text and is read once here. Absent when
    /// the website has no option at all.
    #[serde(default)]
    pub options: Option<String>,
}

impl PublishQuery {
    /// What the editor sent with this publication
    ///
    /// Options nobody could read are no options: publishing a website matters
    /// more than the address it names, and what went wrong is said once in the
    /// log rather than failing the whole request.
    fn options(&self) -> crate::actions::PublicationOptions {
        let Some(options) = self.options.as_deref() else {
            return Default::default();
        };
        serde_json::from_str(options).unwrap_or_else(|e| {
            tracing::warn!("Could not read the options of the publication: {}", e);
            Default::default()
        })
    }
}

/// Publication request body
///
/// The editor also sends the website data and the publication options, which
/// only a hosting service could use. Serde ignores them.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PublishRequest {
    #[serde(default)]
    pub files: Vec<ClientSideFile>,
}

/// A file generated by the editor
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientSideFile {
    /// Path where the file is published
    pub path: String,

    /// Pretty path taking precedence over `path`, when the editor's permalink
    /// plugin rewrites URLs (e.g. `/about` instead of `/about.html`)
    #[serde(default)]
    pub permalink: Option<String>,

    /// File content, for the files the editor generates
    #[serde(default)]
    pub content: Option<String>,

    /// Path of a stored asset, for the files the editor references
    #[serde(default)]
    pub src: Option<String>,
}

/// What publishing answers, the moment the files are written
#[derive(Debug, Serialize)]
pub struct PublishResponse {
    /// Where the website is served
    ///
    /// Always null here, and kept because `{ url, job }` is what the editor's
    /// own type says and what the hosted server answers. Nothing serves the
    /// files at the moment this leaves: where they end up, and whether they
    /// ever do, is what the job says.
    pub url: Option<String>,
    pub job: JobData,
}

/// Which publication the editor is asking about
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StatusQuery {
    pub job_id: String,
}

/// Publish a website
///
/// POST /api/publication/?websiteId=X
async fn publish_website(
    State(state): State<AppState>,
    Query(query): Query<PublishQuery>,
    Json(request): Json<PublishRequest>,
) -> Result<Json<PublishResponse>> {
    let mut files: Vec<File> = Vec::new();

    for file in request.files {
        let content = match (file.content, file.src) {
            (Some(content), _) => content.into_bytes(),
            (None, Some(src)) => {
                let asset_name = asset_name_of(&src);
                storage::read_asset(&state.data_path, &query.website_id, &asset_name).await?
            }
            (None, None) => {
                return Err(Error::InvalidInput(format!(
                    "File '{}' has neither content nor src",
                    file.path
                )))
            }
        };

        files.push(File {
            path: file.permalink.unwrap_or(file.path),
            content,
        });
    }

    publish::publish(&state.data_path, &query.website_id, &files).await?;

    // The files are written, and that is the one thing that can be promised
    // here. Whoever takes them to a forge says the rest through the job, which
    // the editor follows until the forge has answered.
    let job = state.jobs.start(publishing_message(&state.data_path, &query.website_id));
    let answered = state
        .jobs
        .read(job.id())
        .expect("the publication was just opened");

    if let Some(actions) = state.actions.clone() {
        let website_id = query.website_id.clone();
        let options = query.options();
        let data_path = state.data_path.clone();
        // Sending a website runs git over the network, on a thread of its own
        // so that a slow push does not freeze the server
        tokio::task::spawn_blocking(move || {
            actions.deploy(&website_id, &options, &job);
            // A host that has nothing to send the website to, or one that
            // returned without saying how it went, leaves the publication
            // where it really is rather than open forever
            job.succeeded(published_message(&data_path, &website_id));
        });
    } else {
        job.succeeded(published_message(&state.data_path, &query.website_id));
    }

    Ok(Json(PublishResponse {
        url: None,
        job: answered,
    }))
}

/// What the user reads while nobody has said anything yet
///
/// The files are already on the disk at this point, so there is something to
/// open rather than a wait in front of nothing.
fn publishing_message(data_path: &std::path::Path, website_id: &WebsiteId) -> String {
    told("Publishing your website", data_path, website_id)
}

/// What the user reads when the files are all there is to say
fn published_message(data_path: &std::path::Path, website_id: &WebsiteId) -> String {
    told("Your website is published.", data_path, website_id)
}

/// A sentence, and the one button this server can offer with it
///
/// It opens the files the editor generated, not a website a page generator
/// built out of them, and a site whose pages are named by its author may have
/// no `index.html` among them. So it says files on this computer, and never
/// the published website.
fn told(sentence: &str, data_path: &std::path::Path, website_id: &WebsiteId) -> String {
    format!(
        "<p><strong>{}</strong></p>\
         <div class=\"buttons\">\
         <a href=\"{}\" target=\"_blank\" class=\"silex-button silex-button--secondary\">\
         See the files on this computer</a></div>",
        sentence,
        crate::storage::published_files_url(data_path, website_id)
    )
}

/// Where a publication is
///
/// GET /api/publication/publication/status?jobId=X
async fn publication_status(
    State(state): State<AppState>,
    Query(query): Query<StatusQuery>,
) -> Result<Json<JobData>> {
    // A publication nobody knows about is one this server never opened, or one
    // it opened before being restarted. Either way the editor would ask about
    // it forever, so it is told the publication is over and why.
    let job = state.jobs.read(&query.job_id).unwrap_or_else(|| JobData {
        job_id: query.job_id.clone(),
        status: JobStatus::Error,
        message: "<p>Silex lost track of this publication. Publish again to know how it went.</p>"
            .to_string(),
        logs: vec![Vec::new()],
        errors: vec![Vec::new()],
        start_time: 0,
        end_time: None,
    });
    Ok(Json(job))
}

/// Asset name out of the `src` sent by the editor
///
/// The editor is expected to send a stored path, but it has been seen sending
/// an API path or a full URL. Logged so that we can tell what it really sends
/// and drop this if it turns out to be dead weight.
fn asset_name_of(src: &str) -> String {
    tracing::debug!(src = %src, "publish: reading asset");

    if let Some(pos) = src.find("/api/website/assets/") {
        let after = &src[pos + "/api/website/assets/".len()..];
        return after.split('?').next().unwrap_or(after).to_string();
    }

    if let Some(stripped) = src.strip_prefix("/assets/") {
        return stripped.to_string();
    }

    src.to_string()
}
