/*
 * Silex website builder - desktop app.
 * Copyright (c) 2023 lexoyo and Silex Labs foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 */

//! The build of a published website

use std::path::Path;

use serde::Deserialize;

pub const ELEVENTY_VERSION: &str = "3.1.6";

const SILEX_OVERWRITE_NOTICE: &str = "# silexOverwrite: true";
const BUILD_JSON: &str = "build.json";
const BUILD_SH: &str = "build.sh";
const GITIGNORE: &str = ".gitignore";
/// Where build.sh writes the built site, which is not part of the website
const BUILD_OUTPUT: &str = "_site/";
const DEFAULT_BUILD_JSON: &str = "[\n  {\n    \"type\": \"build\"\n  }\n]\n";

#[derive(Debug, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum BuildStep {
    Build,
    Sh { value: String },
}

// The guard is for a public/ with no folder at all: the glob then stays literal
// and cp would stop the build. Nothing is silenced, so that a copy failing for a
// real reason stops the build instead of publishing a website without its
// stylesheet.
const COPY_PUBLIC_FOLDERS: &str = "for dir in public/*/; do [ -d \"$dir\" ] || continue; cp -R \"$dir\" _site/; done";

pub fn generate_build_sh(steps: &[BuildStep]) -> String {
    let build_commands = format!(
        "npx @11ty/eleventy@{ELEVENTY_VERSION} --input=public --output=_site\n{COPY_PUBLIC_FOLDERS}"
    );
    let lines: Vec<String> = steps
        .iter()
        .map(|step| match step {
            BuildStep::Build => build_commands.clone(),
            BuildStep::Sh { value } => value.clone(),
        })
        .collect();
    format!(
        "#!/bin/sh\n# Generated by Silex at each publication, do not edit: customize the build in build.json instead\nset -e\n{}\n",
        lines.join("\n")
    )
}

/// Write build.json and build.sh in the website folder
///
/// build.json is created once and never rewritten afterwards, build.sh always
/// follows what it says.
pub fn ensure_build_files(site: &Path) -> Result<(), String> {
    let build_json = site.join(BUILD_JSON);
    let steps: Vec<BuildStep> = if build_json.exists() {
        let content = std::fs::read_to_string(&build_json).map_err(|e| e.to_string())?;
        serde_json::from_str(&content).map_err(|e| format!("Invalid {}: {}", BUILD_JSON, e))?
    } else {
        std::fs::write(&build_json, DEFAULT_BUILD_JSON).map_err(|e| e.to_string())?;
        vec![BuildStep::Build]
    };

    std::fs::write(site.join(BUILD_SH), generate_build_sh(&steps)).map_err(|e| e.to_string())?;
    ignore_build_output(site)
}

/// Keep the built site out of the versioned website
///
/// The website folder is versioned whole, so running build.sh once would
/// otherwise put a copy of the site in its own history.
fn ignore_build_output(site: &Path) -> Result<(), String> {
    let path = site.join(GITIGNORE);
    let current = std::fs::read_to_string(&path).unwrap_or_default();
    if current.lines().any(|line| line.trim() == BUILD_OUTPUT.trim_end_matches('/')
        || line.trim() == BUILD_OUTPUT)
    {
        return Ok(());
    }

    let mut content = current;
    if !content.is_empty() && !content.ends_with('\n') {
        content.push('\n');
    }
    content.push_str(BUILD_OUTPUT);
    content.push('\n');
    std::fs::write(&path, content).map_err(|e| e.to_string())
}

/// Write the pipeline file, unless the user took it over
///
/// The marker means Silex owns the file; without it the file was customized
/// and it keeps working untouched.
pub fn ensure_pipeline_file(site: &Path, path: &Path, content: &str) -> Result<(), String> {
    let full_path = site.join(path);
    let keep = match std::fs::read_to_string(&full_path) {
        Ok(existing) => !existing.starts_with(SILEX_OVERWRITE_NOTICE),
        Err(_) => false,
    };
    if keep {
        return Ok(());
    }

    if let Some(parent) = full_path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::write(&full_path, content).map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn a_website(name: &str) -> std::path::PathBuf {
        let site = std::env::temp_dir().join(format!("silex-pipeline-{}-{}", name, std::process::id()));
        let _ = std::fs::remove_dir_all(&site);
        std::fs::create_dir_all(&site).unwrap();
        site
    }

    #[test]
    fn the_build_belongs_to_the_user_and_the_script_to_silex() {
        let site = a_website("build");
        ensure_build_files(&site).unwrap();
        let built = generate_build_sh(&[BuildStep::Build]);
        assert!(built.contains("@11ty/eleventy@"));
        // Nothing is silenced: a copy that fails for a real reason stops the
        // build rather than publishing a website without its stylesheet
        assert!(!built.contains("2>/dev/null"), "{}", built);
        assert!(!built.contains("|| true"), "{}", built);
        assert!(built.contains(COPY_PUBLIC_FOLDERS), "{}", built);

        // What the user wrote in build.json is theirs and stays
        std::fs::write(site.join(BUILD_JSON), r#"[{"type":"sh","value":"npx -y pagefind"}]"#).unwrap();
        ensure_build_files(&site).unwrap();
        let build_json = std::fs::read_to_string(site.join(BUILD_JSON)).unwrap();
        assert!(build_json.contains("pagefind"), "build.json was rewritten: {}", build_json);
        // build.sh is generated from it, every time
        let build_sh = std::fs::read_to_string(site.join(BUILD_SH)).unwrap();
        assert!(build_sh.contains("npx -y pagefind"), "{}", build_sh);
        assert!(!build_sh.contains("eleventy"), "the step it no longer asks for: {}", build_sh);

        let _ = std::fs::remove_dir_all(&site);
    }

    fn run_copy_step(site: &Path) {
        let status = std::process::Command::new("sh")
            .arg("-e")
            .arg("-c")
            .arg(COPY_PUBLIC_FOLDERS)
            .current_dir(site)
            .status()
            .unwrap();
        assert!(status.success(), "the copy step stopped the build: {:?}", status);
    }

    #[test]
    fn every_folder_of_the_website_ends_up_in_the_built_site() {
        let site = a_website("copy");
        std::fs::create_dir_all(site.join("public/fonts")).unwrap();
        std::fs::create_dir_all(site.join("public/img/icons")).unwrap();
        std::fs::create_dir_all(site.join("_site")).unwrap();
        std::fs::write(site.join("public/fonts/a.woff"), "font").unwrap();
        std::fs::write(site.join("public/img/icons/b.svg"), "icon").unwrap();

        run_copy_step(&site);

        assert!(site.join("_site/fonts/a.woff").exists());
        assert!(site.join("_site/img/icons/b.svg").exists());

        let _ = std::fs::remove_dir_all(&site);
    }

    #[test]
    fn a_website_with_no_folder_to_copy_still_gets_published() {
        let site = a_website("copy-flat");
        std::fs::create_dir_all(site.join("public")).unwrap();
        std::fs::create_dir_all(site.join("_site")).unwrap();
        std::fs::write(site.join("public/index.html"), "page").unwrap();

        run_copy_step(&site);

        let _ = std::fs::remove_dir_all(&site);
    }

    #[test]
    fn the_built_site_is_ignored_once_and_what_was_there_is_kept() {
        let site = a_website("gitignore");
        std::fs::write(site.join(GITIGNORE), "node_modules").unwrap();

        ensure_build_files(&site).unwrap();
        ensure_build_files(&site).unwrap();

        let gitignore = std::fs::read_to_string(site.join(GITIGNORE)).unwrap();
        assert!(gitignore.contains("node_modules"), "{}", gitignore);
        assert_eq!(gitignore.matches(BUILD_OUTPUT).count(), 1, "{}", gitignore);

        let _ = std::fs::remove_dir_all(&site);
    }

    #[test]
    fn a_pipeline_the_user_took_over_is_left_alone() {
        let site = a_website("pipeline");
        let file = Path::new(".gitlab-ci.yml");

        ensure_pipeline_file(&site, file, "# silexOverwrite: true\nfirst").unwrap();
        ensure_pipeline_file(&site, file, "# silexOverwrite: true\nsecond").unwrap();
        assert!(std::fs::read_to_string(site.join(file)).unwrap().contains("second"));

        // Once the marker is gone, the file is the user's
        std::fs::write(site.join(file), "mine").unwrap();
        ensure_pipeline_file(&site, file, "# silexOverwrite: true\nthird").unwrap();
        assert_eq!(std::fs::read_to_string(site.join(file)).unwrap(), "mine");

        let _ = std::fs::remove_dir_all(&site);
    }
}
