/*
 * Silex website builder, free/libre no-code tool for makers.
 * Copyright (c) 2023 lexoyo and Silex Labs foundation
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 */

import { BuildStep } from '~/common/types.js'

export const ELEVENTY_VERSION = '3.1.6'

export const BUILD_JSON_PATH = 'build.json'
export const BUILD_SH_PATH = 'build.sh'

export const DEFAULT_BUILD_STEPS: BuildStep[] = [{ type: 'build' }]

// || true: sites without images have no assets/ folder in git
const BUILD_COMMANDS = [
  `npx @11ty/eleventy@${ELEVENTY_VERSION} --input=public --output=_site`,
  'cp -R public/css public/assets _site/ 2>/dev/null || true',
]

export function parseBuildSteps(content: string): BuildStep[] {
  const steps = JSON.parse(content)
  if (!Array.isArray(steps)) throw new Error('build.json must be an array of steps')
  steps.forEach((step, i) => {
    if (step?.type === 'build') return
    if (step?.type === 'sh' && typeof step.value === 'string') return
    throw new Error(`build.json step ${i} must be { "type": "build" } or { "type": "sh", "value": "..." }`)
  })
  return steps
}

export function generateBuildSh(steps: BuildStep[]): string {
  const lines = steps.flatMap(step => step.type === 'build' ? BUILD_COMMANDS : [step.value])
  return [
    '#!/bin/sh',
    '# Generated by Silex at each publication, do not edit: customize the build in build.json instead',
    'set -e',
    ...lines,
    '',
  ].join('\n')
}
